/* 유저 */
CREATE TABLE ROCKFEST.MYUSER (
	USER_ID VARCHAR2(15) NOT NULL, /* 아이디 */
	TC_ON_CODE VARCHAR2(50) NOT NULL, /* 예매코드 */
	USER_PW VARCHAR2(20) NOT NULL, /* 비밀번호 */
	USER_NAME VARCHAR2(10) NOT NULL, /* 이름 */
	USER_TEL VARCHAR2(15) NOT NULL, /* 전화 */
	USER_EMAIL VARCHAR2(30) NOT NULL, /* 이메일 */
	USER_ADDR VARCHAR2(100) /* 주소 */
);

COMMENT ON TABLE ROCKFEST.MYUSER IS '유저';

COMMENT ON COLUMN ROCKFEST.MYUSER.USER_ID IS '아이디';

COMMENT ON COLUMN ROCKFEST.MYUSER.TC_ON_CODE IS '예매코드';

COMMENT ON COLUMN ROCKFEST.MYUSER.USER_PW IS '비밀번호';

COMMENT ON COLUMN ROCKFEST.MYUSER.USER_NAME IS '이름';

COMMENT ON COLUMN ROCKFEST.MYUSER.USER_TEL IS '전화';

COMMENT ON COLUMN ROCKFEST.MYUSER.USER_EMAIL IS '이메일';

COMMENT ON COLUMN ROCKFEST.MYUSER.USER_ADDR IS '주소';

CREATE UNIQUE INDEX ROCKFEST.PK_MYUSER
	ON ROCKFEST.MYUSER (
		USER_ID ASC,
		TC_ON_CODE ASC
	);

ALTER TABLE ROCKFEST.MYUSER
	ADD
		CONSTRAINT PK_MYUSER
		PRIMARY KEY (
			USER_ID,
			TC_ON_CODE
		);

/* 예매 */
CREATE TABLE ROCKFEST.TICKETING (
	USER_ID VARCHAR2(15) NOT NULL, /* 아이디 */
	FST_CODE VARCHAR2(50) NOT NULL, /* 공연코드 */
	TC_ON_CODE VARCHAR2(50) NOT NULL, /* 예매코드 */
	TC_ON_BUY NUMBER, /* 온라인티켓구매수량 */
	TC_RECEIVE CHAR(1) NOT NULL /* 수령여부 */
);

COMMENT ON TABLE ROCKFEST.TICKETING IS '예매';

COMMENT ON COLUMN ROCKFEST.TICKETING.USER_ID IS '아이디';

COMMENT ON COLUMN ROCKFEST.TICKETING.FST_CODE IS '공연코드';

COMMENT ON COLUMN ROCKFEST.TICKETING.TC_ON_CODE IS '예매코드';

COMMENT ON COLUMN ROCKFEST.TICKETING.TC_ON_BUY IS '온라인티켓구매수량';

COMMENT ON COLUMN ROCKFEST.TICKETING.TC_RECEIVE IS '수령여부';

CREATE UNIQUE INDEX ROCKFEST.PK_TICKETING
	ON ROCKFEST.TICKETING (
		USER_ID ASC,
		TC_ON_CODE ASC
	);

ALTER TABLE ROCKFEST.TICKETING
	ADD
		CONSTRAINT PK_TICKETING
		PRIMARY KEY (
			USER_ID,
			TC_ON_CODE
		);

/* 굿즈 */
CREATE TABLE ROCKFEST.GOODS (
	FST_CODE VARCHAR2(50) NOT NULL, /* 공연코드 */
	GD_CODE VARCHAR2(15) NOT NULL, /* 굿즈코드 */
	ART_NUM NUMBER NOT NULL, /* 아티스트번호 */
	GD_NAME VARCHAR2(20) NOT NULL, /* 굿즈명 */
	GD_PRICE NUMBER /* 굿즈가격 */
);

COMMENT ON TABLE ROCKFEST.GOODS IS '굿즈';

COMMENT ON COLUMN ROCKFEST.GOODS.FST_CODE IS '공연코드';

COMMENT ON COLUMN ROCKFEST.GOODS.GD_CODE IS '굿즈코드';

COMMENT ON COLUMN ROCKFEST.GOODS.ART_NUM IS '아티스트번호';

COMMENT ON COLUMN ROCKFEST.GOODS.GD_NAME IS '굿즈명';

COMMENT ON COLUMN ROCKFEST.GOODS.GD_PRICE IS '굿즈가격';

CREATE UNIQUE INDEX ROCKFEST.PK_GOODS
	ON ROCKFEST.GOODS (
		GD_CODE ASC
	);

ALTER TABLE ROCKFEST.GOODS
	ADD
		CONSTRAINT PK_GOODS
		PRIMARY KEY (
			GD_CODE
		);

/* 좌석정보 */
CREATE TABLE ROCKFEST.HALL_INFO (
	H_NAME VARCHAR2(20) NOT NULL, /* 공연장 */
	H_SEATS NUMBER /* 총좌석 */
);

COMMENT ON TABLE ROCKFEST.HALL_INFO IS '좌석정보';

COMMENT ON COLUMN ROCKFEST.HALL_INFO.H_NAME IS '공연장';

COMMENT ON COLUMN ROCKFEST.HALL_INFO.H_SEATS IS '총좌석';

CREATE UNIQUE INDEX ROCKFEST.PK_HALL_INFO
	ON ROCKFEST.HALL_INFO (
		H_NAME ASC
	);

ALTER TABLE ROCKFEST.HALL_INFO
	ADD
		CONSTRAINT PK_HALL_INFO
		PRIMARY KEY (
			H_NAME
		);

/* 혜택 */
CREATE TABLE ROCKFEST.SALE (
	SALE_TYPE VARCHAR2(20) NOT NULL, /* 할인종류 */
	SALE_PERC NUMBER /* 할인률(%) */
);

COMMENT ON TABLE ROCKFEST.SALE IS '혜택';

COMMENT ON COLUMN ROCKFEST.SALE.SALE_TYPE IS '할인종류';

COMMENT ON COLUMN ROCKFEST.SALE.SALE_PERC IS '할인률(%)';

CREATE UNIQUE INDEX ROCKFEST.PK_SALE
	ON ROCKFEST.SALE (
		SALE_TYPE ASC
	);

ALTER TABLE ROCKFEST.SALE
	ADD
		CONSTRAINT PK_SALE
		PRIMARY KEY (
			SALE_TYPE
		);

/* 결제 */
CREATE TABLE ROCKFEST.PAY_INFO (
	TC_ON_CODE VARCHAR2(50) NOT NULL, /* 예매코드 */
	USER_ID VARCHAR2(15) NOT NULL, /* 아이디 */
	TC_DATE DATE NOT NULL, /* 예매날짜 */
	PAY NUMBER NOT NULL, /* 결제금액 */
	SALE_TYPE VARCHAR2(20), /* 할인종류 */
	SALE_AM NUMBER, /* 할인액 */
	PAY_F NUMBER NOT NULL, /* 최종결제액 */
	PAY_TYPE VARCHAR2(20) /* 결제수단 */
);

COMMENT ON TABLE ROCKFEST.PAY_INFO IS '결제';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.TC_ON_CODE IS '예매코드';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.USER_ID IS '아이디';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.TC_DATE IS '예매날짜';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.PAY IS '결제금액';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.SALE_TYPE IS '할인종류';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.SALE_AM IS '할인액';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.PAY_F IS '최종결제액';

COMMENT ON COLUMN ROCKFEST.PAY_INFO.PAY_TYPE IS '결제수단';

CREATE UNIQUE INDEX ROCKFEST.PK_PAY_INFO
	ON ROCKFEST.PAY_INFO (
		TC_ON_CODE ASC,
		USER_ID ASC
	);

ALTER TABLE ROCKFEST.PAY_INFO
	ADD
		CONSTRAINT PK_PAY_INFO
		PRIMARY KEY (
			TC_ON_CODE,
			USER_ID
		);

/* 티켓 */
CREATE TABLE ROCKFEST.TICKET (
	FST_CODE VARCHAR2(50) NOT NULL, /* 공연코드 */
	H_NAME VARCHAR2(20) NOT NULL, /* 공연장 */
	TC_S_LOC VARCHAR2(40), /* 판매위치 */
	TC_S_DL DATE, /* 판매마감 */
	TC_MAX NUMBER, /* 구매최대수량_1인 */
	TC_PRICE NUMBER, /* 티켓가격 */
	TC_TOT NUMBER, /* 티켓총수량 */
	TC_REM NUMBER /* 티켓남은수량 */
);

COMMENT ON TABLE ROCKFEST.TICKET IS '티켓';

COMMENT ON COLUMN ROCKFEST.TICKET.FST_CODE IS '공연코드';

COMMENT ON COLUMN ROCKFEST.TICKET.H_NAME IS '공연장';

COMMENT ON COLUMN ROCKFEST.TICKET.TC_S_LOC IS '판매위치';

COMMENT ON COLUMN ROCKFEST.TICKET.TC_S_DL IS '판매마감';

COMMENT ON COLUMN ROCKFEST.TICKET.TC_MAX IS '구매최대수량_1인';

COMMENT ON COLUMN ROCKFEST.TICKET.TC_PRICE IS '티켓가격';

COMMENT ON COLUMN ROCKFEST.TICKET.TC_TOT IS '티켓총수량';

COMMENT ON COLUMN ROCKFEST.TICKET.TC_REM IS '티켓남은수량';

CREATE UNIQUE INDEX ROCKFEST.PK_TICKET
	ON ROCKFEST.TICKET (
		FST_CODE ASC
	);

ALTER TABLE ROCKFEST.TICKET
	ADD
		CONSTRAINT PK_TICKET
		PRIMARY KEY (
			FST_CODE
		);

/* 입장 */
CREATE TABLE ROCKFEST.ADMIN (
	FST_CODE VARCHAR2(50) NOT NULL, /* 공연코드 */
	TOT_BUY_NUM NUMBER, /* 총티켓구매인원 */
	RECEIVE_NUM NUMBER, /* 티켓수령인원 */
	ADMIN_NUM NUMBER /* 입장인원 */
);

COMMENT ON TABLE ROCKFEST.ADMIN IS '입장';

COMMENT ON COLUMN ROCKFEST.ADMIN.FST_CODE IS '공연코드';

COMMENT ON COLUMN ROCKFEST.ADMIN.TOT_BUY_NUM IS '총티켓구매인원';

COMMENT ON COLUMN ROCKFEST.ADMIN.RECEIVE_NUM IS '티켓수령인원';

COMMENT ON COLUMN ROCKFEST.ADMIN.ADMIN_NUM IS '입장인원';

CREATE UNIQUE INDEX ROCKFEST.PK_ADMIN
	ON ROCKFEST.ADMIN (
		FST_CODE ASC
	);

ALTER TABLE ROCKFEST.ADMIN
	ADD
		CONSTRAINT PK_ADMIN
		PRIMARY KEY (
			FST_CODE
		);

/* 현장구매 */
CREATE TABLE ROCKFEST.BOX_OF (
	FST_CODE VARCHAR2(50) NOT NULL, /* 공연코드 */
	BOO_CODE VARCHAR2(20) NOT NULL, /* 부스코드 */
	BOO_LOC VARCHAR2(100), /* 부스위치 */
	TC_OFF_BUY NUMBER /* 현장티켓구매수량 */
);

COMMENT ON TABLE ROCKFEST.BOX_OF IS '현장구매';

COMMENT ON COLUMN ROCKFEST.BOX_OF.FST_CODE IS '공연코드';

COMMENT ON COLUMN ROCKFEST.BOX_OF.BOO_CODE IS '부스코드';

COMMENT ON COLUMN ROCKFEST.BOX_OF.BOO_LOC IS '부스위치';

COMMENT ON COLUMN ROCKFEST.BOX_OF.TC_OFF_BUY IS '현장티켓구매수량';

CREATE UNIQUE INDEX ROCKFEST.PK_BOX_OF
	ON ROCKFEST.BOX_OF (
		BOO_CODE ASC
	);

ALTER TABLE ROCKFEST.BOX_OF
	ADD
		CONSTRAINT PK_BOX_OF
		PRIMARY KEY (
			BOO_CODE
		);

/* 직원 */
CREATE TABLE ROCKFEST.EMP (
	BOO_CODE VARCHAR2(20) NOT NULL, /* 부스코드 */
	EMPNO NUMBER NOT NULL, /* 사원번호 */
	ENAME VARCHAR2(20), /* 사원이름 */
	ETEL VARCHAR2(20), /* 전화번호 */
	DEPTNO NUMBER /* 부서번호 */
);

COMMENT ON TABLE ROCKFEST.EMP IS '직원';

COMMENT ON COLUMN ROCKFEST.EMP.BOO_CODE IS '부스코드';

COMMENT ON COLUMN ROCKFEST.EMP.EMPNO IS '사원번호';

COMMENT ON COLUMN ROCKFEST.EMP.ENAME IS '사원이름';

COMMENT ON COLUMN ROCKFEST.EMP.ETEL IS '전화번호';

COMMENT ON COLUMN ROCKFEST.EMP.DEPTNO IS '부서번호';

CREATE UNIQUE INDEX ROCKFEST.PK_EMP
	ON ROCKFEST.EMP (
		BOO_CODE ASC,
		EMPNO ASC
	);

ALTER TABLE ROCKFEST.EMP
	ADD
		CONSTRAINT PK_EMP
		PRIMARY KEY (
			BOO_CODE,
			EMPNO
		);

/* 재고 */
CREATE TABLE ROCKFEST.GOODS_BALANCE (
	GD_CODE VARCHAR2(15) NOT NULL, /* 굿즈코드 */
	WH_CODE VARCHAR2(20) NOT NULL, /* 창고위치 */
	WH_LOC NUMBER /* 재고수량 */
);

COMMENT ON TABLE ROCKFEST.GOODS_BALANCE IS '재고';

COMMENT ON COLUMN ROCKFEST.GOODS_BALANCE.GD_CODE IS '굿즈코드';

COMMENT ON COLUMN ROCKFEST.GOODS_BALANCE.WH_CODE IS '창고위치';

COMMENT ON COLUMN ROCKFEST.GOODS_BALANCE.WH_LOC IS '재고수량';

CREATE UNIQUE INDEX ROCKFEST.PK_GOODS_BALANCE
	ON ROCKFEST.GOODS_BALANCE (
		GD_CODE ASC
	);

ALTER TABLE ROCKFEST.GOODS_BALANCE
	ADD
		CONSTRAINT PK_GOODS_BALANCE
		PRIMARY KEY (
			GD_CODE
		);

ALTER TABLE ROCKFEST.TICKETING
	ADD
		CONSTRAINT FK_TICKET_TO_TICKETING
		FOREIGN KEY (
			FST_CODE
		)
		REFERENCES ROCKFEST.TICKET (
			FST_CODE
		);

ALTER TABLE ROCKFEST.TICKETING
	ADD
		CONSTRAINT FK_MYUSER_TO_TICKETING
		FOREIGN KEY (
			USER_ID,
			TC_ON_CODE
		)
		REFERENCES ROCKFEST.MYUSER (
			USER_ID,
			TC_ON_CODE
		);

ALTER TABLE ROCKFEST.GOODS
	ADD
		CONSTRAINT FK_TICKET_TO_GOODS
		FOREIGN KEY (
			FST_CODE
		)
		REFERENCES ROCKFEST.TICKET (
			FST_CODE
		);

ALTER TABLE ROCKFEST.PAY_INFO
	ADD
		CONSTRAINT FK_SALE_TO_PAY_INFO
		FOREIGN KEY (
			SALE_TYPE
		)
		REFERENCES ROCKFEST.SALE (
			SALE_TYPE
		);

ALTER TABLE ROCKFEST.PAY_INFO
	ADD
		CONSTRAINT FK_TICKETING_TO_PAY_INFO
		FOREIGN KEY (
			USER_ID,
			TC_ON_CODE
		)
		REFERENCES ROCKFEST.TICKETING (
			USER_ID,
			TC_ON_CODE
		);

ALTER TABLE ROCKFEST.TICKET
	ADD
		CONSTRAINT FK_HALL_INFO_TO_TICKET
		FOREIGN KEY (
			H_NAME
		)
		REFERENCES ROCKFEST.HALL_INFO (
			H_NAME
		);

ALTER TABLE ROCKFEST.ADMIN
	ADD
		CONSTRAINT FK_TICKET_TO_ADMIN
		FOREIGN KEY (
			FST_CODE
		)
		REFERENCES ROCKFEST.TICKET (
			FST_CODE
		);

ALTER TABLE ROCKFEST.BOX_OF
	ADD
		CONSTRAINT FK_TICKET_TO_BOX_OF
		FOREIGN KEY (
			FST_CODE
		)
		REFERENCES ROCKFEST.TICKET (
			FST_CODE
		);

ALTER TABLE ROCKFEST.EMP
	ADD
		CONSTRAINT FK_BOX_OF_TO_EMP
		FOREIGN KEY (
			BOO_CODE
		)
		REFERENCES ROCKFEST.BOX_OF (
			BOO_CODE
		);

ALTER TABLE ROCKFEST.GOODS_BALANCE
	ADD
		CONSTRAINT FK_GOODS_TO_GOODS_BALANCE
		FOREIGN KEY (
			GD_CODE
		)
		REFERENCES ROCKFEST.GOODS (
			GD_CODE
		);